{% set name = "codemodel" %}
{% set version = "0.0.7" %}
{% set sha256 = "d03ca24585d867754ca0f34aba2c577f83386425251d2f283be4fbbad35bcf60" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - astor
    - black
    - isort >=5

test:
  requires:
    - python {{ python_min }}
  imports:
    - codemodel

about:
  home: https://github.com/dwhswenson/codemodel
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Advanced metaprogramming tools
  description: |
    Advanced metaprogramming tools.
  doc_url: https://codemodel.readthedocs.io/
  dev_url: https://github.com/dwhswenson/codemodel

extra:
  recipe-maintainers:
    - dwhswenson
